<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "isan_blog"
 *
 * Auto generated by Extension Builder 2016-02-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'I-SAN Blog',
	'description' => 'Eine Extbase Blog-Extension die Einträge als Seiten organisiert.',
	'category' => 'plugin',
	'author' => 'Sebastian Antosch, Christian Baur',
	'author_email' => 's.antosch@i-san.de, c.baur@i-san.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);